// ITEM Events
export  const ITEM_INSERT = "ITEM_INSERT"
export  const ITEM_UPDATE = "ITEM_UPDATE"
export  const ITEM_DELETE = "ITEM_DELETE"
// #END#

// CATEGORY Events
export  const CATEGORY_INSERT = "CATEGORY_INSERT"
export  const CATEGORY_UPDATE = "CATEGORY_UPDATE"
export  const CATEGORY_DELETE = "CATEGORY_DELETE"
// #END#

// DISCOUNT Events
export  const DISCOUNT_INSERT = "DISCOUNT_INSERT"
export  const DISCOUNT_UPDATE = "DISCOUNT_UPDATE"
export  const DISCOUNT_DELETE = "DISCOUNT_DELETE"
// #END#

// MODIFIER Events
export  const MODIFIER_INSERT = "MODIFIER_INSERT"
export  const MODIFIER_UPDATE = "MODIFIER_UPDATE"
export  const MODIFIER_DELETE = "MODIFIER_DELETE"
// #END#

// RECEIPTS Events
export  const REFUND_RECEIPT = "REFUND_RECEIPT"
// #END#